// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package rpcpb is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	RPCInfo
	ResultInfo
*/
package rpcpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RPCInfo struct {
	Cid      string   `protobuf:"bytes,1,opt,name=Cid" json:"Cid,omitempty"`
	Fn       string   `protobuf:"bytes,2,opt,name=Fn" json:"Fn,omitempty"`
	ReplyTo  string   `protobuf:"bytes,3,opt,name=ReplyTo" json:"ReplyTo,omitempty"`
	Track    string   `protobuf:"bytes,4,opt,name=track" json:"track,omitempty"`
	Expired  int64    `protobuf:"varint,5,opt,name=Expired" json:"Expired,omitempty"`
	Reply    bool     `protobuf:"varint,6,opt,name=Reply" json:"Reply,omitempty"`
	ArgsType []string `protobuf:"bytes,7,rep,name=ArgsType" json:"ArgsType,omitempty"`
	Args     [][]byte `protobuf:"bytes,8,rep,name=Args,proto3" json:"Args,omitempty"`
}

func (m *RPCInfo) Reset()                    { *m = RPCInfo{} }
func (m *RPCInfo) String() string            { return proto.CompactTextString(m) }
func (*RPCInfo) ProtoMessage()               {}
func (*RPCInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RPCInfo) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *RPCInfo) GetFn() string {
	if m != nil {
		return m.Fn
	}
	return ""
}

func (m *RPCInfo) GetReplyTo() string {
	if m != nil {
		return m.ReplyTo
	}
	return ""
}

func (m *RPCInfo) GetTrack() string {
	if m != nil {
		return m.Track
	}
	return ""
}

func (m *RPCInfo) GetExpired() int64 {
	if m != nil {
		return m.Expired
	}
	return 0
}

func (m *RPCInfo) GetReply() bool {
	if m != nil {
		return m.Reply
	}
	return false
}

func (m *RPCInfo) GetArgsType() []string {
	if m != nil {
		return m.ArgsType
	}
	return nil
}

func (m *RPCInfo) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

type ResultInfo struct {
	Cid         string   `protobuf:"bytes,1,opt,name=Cid" json:"Cid,omitempty"`
	Error       string   `protobuf:"bytes,2,opt,name=Error" json:"Error,omitempty"`
	ErrCode     int32    `protobuf:"varint,3,opt,name=ErrCode" json:"ErrCode,omitempty"`
	ResultsType []string `protobuf:"bytes,4,rep,name=ResultsType" json:"ResultsType,omitempty"`
	Results     [][]byte `protobuf:"bytes,5,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (m *ResultInfo) Reset()                    { *m = ResultInfo{} }
func (m *ResultInfo) String() string            { return proto.CompactTextString(m) }
func (*ResultInfo) ProtoMessage()               {}
func (*ResultInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResultInfo) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *ResultInfo) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ResultInfo) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ResultInfo) GetResultsType() []string {
	if m != nil {
		return m.ResultsType
	}
	return nil
}

func (m *ResultInfo) GetResults() [][]byte {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCInfo)(nil), "rpcpb.RPCInfo")
	proto.RegisterType((*ResultInfo)(nil), "rpcpb.ResultInfo")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xd3, 0x6c, 0xdb, 0x51, 0x44, 0xc2, 0x1e, 0x06, 0x4f, 0x61, 0x4f, 0x39, 0x79,
	0xf1, 0x09, 0xa4, 0xec, 0x82, 0x37, 0x19, 0xf6, 0x05, 0xdc, 0x36, 0xca, 0xe2, 0xd2, 0x84, 0xd9,
	0x0a, 0xf6, 0x15, 0x7c, 0x25, 0x5f, 0x4e, 0x3a, 0xb1, 0xe2, 0x65, 0x6f, 0xff, 0xf7, 0x33, 0x09,
	0xff, 0xff, 0x43, 0xc3, 0xa9, 0xbb, 0x4f, 0x1c, 0xc7, 0x68, 0x0d, 0xa7, 0x2e, 0x1d, 0x36, 0xdf,
	0x0a, 0x2a, 0x7a, 0x6e, 0x9f, 0x86, 0xd7, 0x68, 0x6f, 0x41, 0xb7, 0xc7, 0x1e, 0x95, 0x53, 0xbe,
	0xa1, 0x59, 0xda, 0x1b, 0x28, 0x76, 0x03, 0x16, 0x62, 0x14, 0xbb, 0xc1, 0x22, 0x54, 0x14, 0xd2,
	0x69, 0xda, 0x47, 0xd4, 0x62, 0x2e, 0x68, 0xd7, 0x60, 0x46, 0x7e, 0xe9, 0xde, 0xb1, 0x14, 0x3f,
	0xc3, 0x7c, 0xbf, 0xfd, 0x4c, 0x47, 0x0e, 0x3d, 0x1a, 0xa7, 0xbc, 0xa6, 0x05, 0xe7, 0x7b, 0x79,
	0x8a, 0x2b, 0xa7, 0x7c, 0x4d, 0x19, 0xec, 0x1d, 0xd4, 0x8f, 0xfc, 0x76, 0xde, 0x4f, 0x29, 0x60,
	0xe5, 0xb4, 0x6f, 0xe8, 0x8f, 0xad, 0x85, 0x72, 0xd6, 0x58, 0x3b, 0xed, 0xaf, 0x49, 0xf4, 0xe6,
	0x4b, 0x01, 0x50, 0x38, 0x7f, 0x9c, 0xc6, 0x0b, 0x05, 0xd6, 0x60, 0xb6, 0xcc, 0x91, 0x7f, 0x3b,
	0x64, 0x90, 0x58, 0xcc, 0x6d, 0xec, 0x83, 0xd4, 0x30, 0xb4, 0xa0, 0x75, 0x70, 0x95, 0xff, 0xcb,
	0x19, 0x4a, 0xc9, 0xf0, 0xdf, 0xca, 0x13, 0x08, 0xa2, 0x91, 0x24, 0x0b, 0x1e, 0x56, 0x32, 0xec,
	0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0xee, 0x88, 0x61, 0x65, 0x01, 0x00, 0x00,
}
